[dev]
   command = "npm run dev"
[build]
  command = "npm run generate"
  publish = "dist"
  functions = 'functions'

[[redirects]]
    from="/api/*"
    to="/.netlify/functions/:splat"
    status=200

    [[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"
  exclude = [
    './build-dir/200.html'
  ]